version: '3.9'
services:
  app:
    build: .
    volumes:
      - "./:/app"
      - gem_cache:/usr/local/bundle
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${DATABASE_USER}:${DATABASE_PASS}@db:5432/my_database
      DATABASE_HOST: ${DATABASE_HOST}
      RACK_ENV: ${RACK_ENV}
    command: bundle exec falcon serve --bind http://0.0.0.0:3000 --count 2

  db:
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: my_database
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - my_network

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - my_network

volumes:
  db_data:
  gem_cache:

networks:
  my_network:
    driver: bridge
