version: '3.9'
services:
  app:
    build: .
    volumes:
      - "./:/app"
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASS: ${DATABASE_PASS}
      WEB_CONCURRENCY: 2  # forks
      MAX_THREADS: 6      # threads
    command: bundle exec falcon serve --bind "http://0.0.0.0:3000"

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: my_database
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - my_network

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:
    driver: bridge
